### ISSUE TITLE
How to add media/upload.json to this project?

### ISSUE THREAD

**Issue by huafsud** [fa0311/twitter-openapi#13]
Hi @fa0311 
this is a great project,and I really love it. 
and I would like to build a scheduled tweet bot based on this Twitter API project. 
It needs to upload images and videos to post. 
I found that Twitter has three states for uploading media:

```
--------INIT ------------
[POST] https://upload.twitter.com/i/media/upload.json?command=INIT&total_bytes=1856821&media_type=video/mp4&video_duration_ms=11562.086000000001&media_category=tweet_video

--------APPEND-----------
[POST] https://upload.twitter.com/i/media/upload.json?command=APPEND&media_id=1676995058216890369&segment_index=0
[POST] https://upload.twitter.com/i/media/upload.json?command=APPEND&media_id=1676995058216890369&segment_index=1

-------FINALIZE---------- State
[POST] https://upload.twitter.com/i/media/upload.json?command=FINALIZE&media_id=1676995058216890369&allow_async=true

```
Since these three states use the same`upload.json` url
but with different parameters, and the request body for the APPEND api requires uploading file data, 
and each state returns a different response,

I'm not sure how to write`placeholder.json` and`build_config.py` to make it work.

Thank you for your open source project, it's really amazing.

**Comment by fa0311** [comment]
Can you write according to the OpenAPI specification?

I will modify it to `placeholder.json`.

**Comment by huafsud** [comment]
I have used the format of twitter-openapi, 
but I'm not sure if it's working correctly. 

but, the response body has mostly the same fields. so `INIT` and `FINALIZE` can use the same of `MediaUploadResponse`

--------INIT ------------

[POST] https://upload.twitter.com/i/media/upload.json?command=INIT&total_bytes=1856821&media_type=video/mp4&video_duration_ms=11562.086000000001&media_category=tweet_video

[response body] {"media_id":1677217907460407298,"media_id_string":"1677217907460407298","expires_after_secs":86399,"media_key":"7_1677217907460407298"}


--------APPEND-----------

[POST] https://upload.twitter.com/i/media/upload.json?command=APPEND&media_id=1677217907460407298&segment_index=0
[response body] 


-------FINALIZE----------

https://upload.twitter.com/i/media/upload.json?command=FINALIZE&media_id=1677217907460407298&allow_async=true

[response body] {"media_id":1677217907460407298,"media_id_string":"1677217907460407298","media_key":"7_1677217907460407298","size":1856821,"expires_after_secs":86400,"processing_info":{"state":"pending","check_after_secs":1}}




```
openapi: 3.0.3
info:
  title: Twitter OpenAPI
  version: 0.0.1

paths:
  /i/media/upload.json:
    post:
      operationId: postMediaUpload
      description: post media upload
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MediaUploadResponse"
      tags:
        - "v-media-post"

#  {"media_id":1677217907460407298,"media_id_string":"1677217907460407298",
#"expires_after_secs":86399,"media_key":"7_1677217907460407298"}

#  {"media_id":1677217907460407298,"media_id_string":"1677217907460407298",
#"media_key":"7_1677217907460407298","size":1856821,
#"expires_after_secs":86400,
#"processing_info":{"state":"pending","check_after_secs":1}}
components:
  schemas:
    MediaUploadResponse:
      required:
        - "media_id"
        - "media_id_string"
        - "media_key"
        - "expires_after_secs"
      properties:
        media_id:
          type: "integer"
        media_id_string:
          type: "string"
        media_key:
          type: "string"
        expires_after_secs:
          type: "integer"
        processing_info:
          $ref: "#/components/schemas/MediaUploadResponseProcessingInfo"



    MediaUploadResponseProcessingInfo:
      properties:
        state:
          type: "string"
        check_after_secs:
          type: "integer"

```


or download this yaml file 

[v-media-post.yaml.txt](https://github.com/fa0311/twitter-openapi/files/11979252/v-media-post.yaml.txt)

**Comment by huafsud** [comment]
hi fa0311:

I don't know how to write the URL request JSON format rules in `placeholder.json`. It's a  complicated.

**Comment by fa0311** [comment]
> It's a complicated.

You're right about that.

It seems that this request cannot be written with the current json rules, so it would be better to write it according to openapi in a straightforward manner.
send us a pull request and we'll merge it in.

**Comment by huafsud** [comment]
ok
