### ISSUE TITLE
Actions for Bookmarking

### ISSUE THREAD

**Issue by AmirAshvins** [fa0311/twitter-openapi#63]
I noticed that the apis for creating and destroying bookmarks of a tweet are not included in this implementation. Is there a way to hopefully add that? 

Thanks a lot

**Comment by fa0311** [comment]
Thanks for reporting back! Added!

**Comment by AmirAshvins** [comment]
Thank a lot for adding it this fast. It's awesome.

I would also love to kindly ask if it's possible to update the twitter_openapi_python repo as well. It would be amazing if that could happen.

All the best

**Comment by fa0311** [comment]
> I would also love to kindly ask if it's possible to update the twitter_openapi_python repo as well. It would be amazing if that could happen.

Updated twitter_openapi_python
